name: elite_counsel
description: A new Flutter application.
publish_to: 'none'
version: 1.0.3-beta.4+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  accordion: ^2.1.2
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  cloud_firestore: ^2.2.0
  date_field: ^2.0.1
  device_preview: ^1.0.0
  dio: ^4.0.6
  dot_navigation_bar: ^1.0.1+3
  equatable: ^2.0.3
  file_picker: ^4.1.1
  firebase_auth: ^3.1.1
  firebase_core: ^1.2.0
  firebase_crashlytics: ^1.0.0
  firebase_storage: ^10.0.3
  floating_bottom_navigation_bar: ^1.5.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_easyloading: ^3.0.0
  flutter_feather_icons: ^2.0.0+1
  flutter_html: null
  flutter_linkify: ^5.0.0
  flutter_neumorphic:
    git:
      url: https://github.com/tsvillain/Flutter-Neumorphic.git
  flutter_svg: ^0.23.0+1
  hive: ^2.1.0
  hive_flutter: ^1.0.0
  image_picker: ^0.8.4+4
  in_app_review: ^2.0.2
  intl: ^0.17.0
  intl_phone_field: ^2.0.0
  ionicons: ^0.1.2
  linkify: ^4.0.0
  liquid_swipe: ^2.1.0
  mime: ^1.0.0
  mockito: ^5.1.0
  open_file: ^3.1.0
  palette_generator: ^0.3.0
  path_provider: ^2.0.1
  percent_indicator: ^3.0.1
  permission_handler: ^8.1.1
  photo_view: ^0.12.0
  pretty_dio_logger: ^1.2.0-beta-1
  random_string: ^2.3.1
  rating_dialog: ^2.0.3
  ripple_navigation: ^1.0.5
  salesiq_mobilisten: ^1.0.1
  share: ^2.0.4
  sms_autofill: ^2.2.0
  store_redirect: ^2.0.0
  timelines: ^0.1.0
  url_launcher: ^6.0.3
  uuid: ^3.0.6
  visibility_detector: ^0.2.0
  youtube_player_flutter: ^8.0.0
  youtube_player_iframe: ^2.2.2
  zoho_chat: ^0.0.1

dev_dependencies:
  dart_code_metrics: ^4.14.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

#  fonts:
#    - family:  Metropolis
#      fonts:
#        - asset: assets/fonts/Metropolis/Metropolis-Black.otf
#          weight: 900
#        - asset: assets/fonts/Metropolis/Metropolis-ExtraBold.otf
#          weight: 800
#        - asset: assets/fonts/Metropolis/Metropolis-Bold.otf
#          weight: 700
#        - asset: assets/fonts/Metropolis/Metropolis-SemiBold.otf
#          weight: 600
#        - asset: assets/fonts/Metropolis/Metropolis-Medium.otf
#          weight: 500
#        - asset: assets/fonts/Metropolis/Metropolis-Regular.otf
#          weight: 400
#        - asset: assets/fonts/Metropolis/Metropolis-Light.otf
#          weight: 300
#        - asset: assets/fonts/Metropolis/Metropolis-ExtraLight.otf
#          weight: 200
#        - asset: assets/fonts/Metropolis/Metropolis-Thin.otf
#          weight: 200
#        - asset: assets/fonts/Metropolis/Metropolis-BlackItalic.otf
#          style: italic
#          weight: 900
#        - asset: assets/fonts/Metropolis/Metropolis-ExtraBoldItalic.otf
#          style: italic
#          weight: 800
#        - asset: assets/fonts/Metropolis/Metropolis-BoldItalic.otf
#          style: italic
#          weight: 700
#        - asset: assets/fonts/Metropolis/Metropolis-SemiBoldItalic.otf
#          style: italic
#          weight: 600
#        - asset: assets/fonts/Metropolis/Metropolis-MediumItalic.otf
#          style: italic
#          weight: 500
##        - asset: assets/fonts/Metropolis/Metropolis-Italic.otf
##          style: italic
##          weight: 400
#        - asset: assets/fonts/Metropolis/Metropolis-LightItalic.otf
#          style: italic
#          weight: 300
#        - asset: assets/fonts/Metropolis/Metropolis-ExtraLightItalic.otf
#          style: italic
#          weight: 200
#        - asset: assets/fonts/Metropolis/Metropolis-ThinItalic.otf
#          style: italic
#          weight: 200
